FROM public.ecr.aws/lts/ubuntu:20.04_stable

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/ /etc/localtime && echo  > /etc/timezone

RUN apt update && apt install aria2 rsync git wget tmux tree -y

RUN git clone -b v2.3.0 --single-branch https://github.com/deepmind/alphafold.git /alphafold
